import { reactive, computed } from 'vue'

// ─── 全局单例语言状态 ───────────────────────────────────────────
const state = reactive({ lang: 'en' })

// ─── 词条字典 ────────────────────────────────────────────────────
const messages = {
  en: {
    // ── NavBar ──────────────────────────────────────────────────
    navCompare:   'COMPARE',
    navGenerate:  'GENERATE',
    navAnalyze:   'ANALYZE',
    navMethod:    'METHOD',

    // ── ModelTrainingOverview ────────────────────────────────────
    row01Title:     'Model Training & Pattern Overview',
    methodPipeline: '1. METHODOLOGY PIPELINE',
    defaultSteps: [
      'Scene Image',
      'OvSGTR Scene Graph',
      'gSpan Frequent Subgraph Mining',
      'Pattern-count Featurization',
      'XGBoost Spatial Scoring',
      'TreeSHAP Contribution Analysis'
    ],
    trainingAssetsTag: 'TRAINING ASSETS',
    trainImages:   'Training Image Samples',
    trainFeatures: 'gSpan Extracted Features',
    cvRmse:        'Cross-Validation RMSE (CV RMSE):',
    cvR2:          'Cross-Validation R² (CV R²):',
    holdoutR2:     'Independent Test Set R² (Holdout R²):',
    fitShapTag:    'FIT & GLOBAL SHAP SUMMARY (DOUBLED SCATTER & IMPORTANCE BAR)',
    scatterPlot:   'Prediction Scatter Plot',
    shapRanking:   'SHAP Global Feature Importance (Top 20)',
    patternSection:'2. INFLUENTIAL SPATIAL PATTERNS',
    patternTip:    'Click a subgraph card to lock it and link to the right-side Evidence Chain for spatial defect analysis.',
    posTitle:      'Promoting Patterns (Top Positive by SHAP)',
    negTitle:      'Suppressing Patterns (Top Negative by SHAP)',
    support:       'Support',
    freq:          'Freq',
    closeModal:    'Click anywhere to close',

    // ── SingleCaseEvidenceChain ──────────────────────────────────
    row03Title:    'Case Optimization Evidence Chain',
    stageBefore:   'Before',
    stageBeforeSub:'Original & Defect Diagnosis',
    stagePlanned:  'Planned',
    stagePlannedSub:'Counterfactual Pattern Plan',
    stageObserved: 'Observed',
    stageObservedSub:'Post-optimization Comparison',
    imageViewTag:  'IMAGE VIEW & DETECTED BBOX',
    patternLockHint: 'Pattern Locked:',
    noPatternHint: 'Click a pattern card on the left to lock it and highlight related spatial elements.',
    shapWaterfall: 'SHAP WATERFALL (Model Decision & Feature Contribution)',
    sceneGraph:    'SCENE GRAPH',
    caseSelector:  'CASE SELECTOR',
    selectCase:    'Select a case to start analysis',
    loading:       'FETCHING CASE ASSETS...',
    sceneGraphTopology: 'SCENE GRAPH TOPOLOGY',
    cyTip:         'Drag nodes to adjust layout · Hover to view semantic relationship',
    spatialDiagnosticReport: 'SPATIAL DIAGNOSTIC REPORT',
    defectDiagnosis: 'Spatial Defect Diagnosis',
    plannedActions:  'Planned Actions & AIGC Prompts',
    observedOutcomes: 'Observed Outcomes & Assessment',
    plannedGain:     'Planned Gain:',
    actualGain:      'Actual Gain:',
    noReportData:    'No diagnostic report data available.',

    // ── GpsCaseSelector ──────────────────────────────────────────
    row02Title:      'GPS Case Directory',
    gpsSiteLegend:   'EXIF Geolocation sites in Fuxing Island',
    waterfront:      'Waterfront',
    publicSpace:     'Public Space',
    heritage:        'Heritage',
    temporary:       'Temporary',
    gpsType:         'Type:',

    // ── GeneratePage ──────────────────────────────────────────────
    pageSubtitle:    'AIGC Urban Design Assessment & Spatial Inference Platform',
    integrityAlert:  'Data Integrity Validation Alert (Missing Files Checked by sync script):',

    // ── MetricsDisplay ────────────────────────────────────────────
    unitItem:        'unit(s)',
    entityAdd:       'Spatial Entity Added',
    entityRemove:    'Spatial Entity Suppressed/Reduced',

    // ── GPS Cases Translation ─────────────────────────────────────
    '杨树浦滨水绿带过渡点 (滨水空间 02)': 'Yangshupu Waterfront Greenbelt (Waterfront 02)',
    '复兴岛运河滨水休闲步道 (滨水空间 03)': 'Fuxing Island Canal Promenade (Waterfront 03)',
    '厂房转角开放式漫步小广场 (公共空间 04)': 'Open Corner Pedestrian Plaza (Public Space 04)',
    '定海路社区生活混合型街道 (公共空间 05)': 'Dinghai Road Mixed Community Street (Public Space 05)',
    '国棉九厂老厂房红砖围墙界面 (景观/工业遗存 01)': 'Cotton Mill No.9 Red-brick Wall Facade (Heritage 01)',
    '复兴岛老旧厂房修缮保护立面 (景观/工业遗存 08)': 'Fuxing Island Factory Facade Restoration (Heritage 08)',
    '厂区外行道绿地口袋休憩点 (临时构筑 06)': 'Roadside Pocket Green Space (Temporary 06)',
    '老街角非正式集市与售货摊区 (临时构筑 07)': 'Informal Market Street Corner (Temporary 07)',

    // ── AbovePage ─────────────────────────────────────────────────
    heroTitle:       'FUXING ISLAND',
    heroSubtitle:    'INNOVATION GRAVITY FIELD',
    heroDesc:        'From Data Diagnosis to Spatial Activation — Multi-modal Indicator-based Innovation Space Identification',
    exploreBtn:      'START EXPLORING',
    screensTitle:    'COMPARISON GALLERY',
    screensDesc:     'BEFORE vs AIGC RESTORATION',
    sceneLegendTitle: 'ZONE LEGEND',
    legendCore:      'CORE INNOVATION',
    legendActivated: 'TO BE ACTIVATED',
    legendTrigger:   'POTENTIAL TRIGGER',
    legendDevelopment: 'UNDER DEVELOPMENT',
    sceneHint:       'DRAG TO ROTATE · SCROLL TO ZOOM',

    // ── StatList ──────────────────────────────────────────────────
    statisticsTag:   'STATISTICS',
    indicatorAnalysisTitle: 'INDICATOR ANALYSIS',
    dataPoints:      'DATA POINTS',
    studyArea:       'STUDY AREA',
    resolution:      'RESOLUTION',
    gridsUnit:       'grids',
    centralShanghai: 'Central Shanghai',
    'MEAN VALUE':    'MEAN VALUE',
    'STD DEVIATION': 'STD DEVIATION',
    'HIGH VALUE':    'HIGH VALUE',
    'LOW VALUE':     'LOW VALUE',

    // ── AnalysisPage ──────────────────────────────────────────────
    dataIntelligence: 'DATA INTELLIGENCE',
    spatialTitle:    'SPATIAL DISTRIBUTION ANALYSIS',
    spatialSubtitle: 'Innovation element collection and clustering visualization across central Shanghai',
    explicitSource:  'EXPLICIT — 15 indicators: land use, density, accessibility, etc.',
    implicitSource:  'IMPLICIT — 6 LLM-derived streetscape perception dimensions',
    quadrantTitle:   'REGION CLASSIFICATION & TRAINING SAMPLES',
    quadrantMap:     'FOUR QUADRANT MAP',
    explicitImplicit: 'EXPLICIT × IMPLICIT',
    trainingDataSamples: 'TRAINING DATA SAMPLES',
    regionStatistics: 'REGION STATISTICS',
    samplesBadge:    'SAMPLES',
    totalBadge:      'TOTAL',
    quadrantQ1:      'High Explicit & High Implicit',
    quadrantQ2:      'Low Explicit & High Implicit',
    quadrantQ3:      'Low Explicit & Low Implicit',
    quadrantQ4:      'High Explicit & Low Implicit',

    // ── MethodPage ────────────────────────────────────────────────
    methodBrand:     'METHODOLOGY',
    chapterOne:      'CHAPTER ONE',
    chapterOneTitle: 'RESEARCH FRAMEWORK',
    chapterOneDesc:  'A multi-dimensional indicator system fusing explicit geospatial data with implicit streetscape perception to identify innovation space types across Shanghai.',
    coreIdeaText:    'This research constructs a multi-dimensional indicator system that fuses explicit geospatial data with implicit streetscape perception data, identifying Shanghai\'s innovation space typologies and generalizing the model to guide Fuxing Island\'s urban renewal design.',
    chapterTwo:      'CHAPTER TWO',
    chapterTwoTitle: 'INDICATOR SYSTEM',
    chapterTwoDesc:  '14 dimensions across two categories — explicit structural data and implicit perceptual signals.',
    explicitIndicatorsTitle: 'EXPLICIT INDICATORS',
    implicitIndicatorsTitle: 'IMPLICIT INDICATORS',
    dimensionsCount8: '8 DIMENSIONS',
    dimensionsCount6: '6 DIMENSIONS',
    llmNoteText:     'Implicit indicators are derived from Large Language Model (LLM) multi-dimensional recognition of streetscape imagery.',
    chapterThree:    'CHAPTER THREE',
    chapterThreeTitle: 'TECHNICAL IMPLEMENTATION',
    chapterThreeDesc: 'LLM-powered perception scoring and density-based clustering algorithms.',
    techPipelineTag: 'PIPELINE',
    techPipelineTitle: 'LLM RECOGNITION FLOW',
    techInput:       'INPUT',
    techInputVal:    'Streetscape Image',
    techProcess:     'PROCESS',
    techProcessVal:  'Large Language Model',
    techProcessSub:  'Vision-Language Understanding',
    techOutput:      'OUTPUT',
    techOutputVal:   '6D Score Vector',
    techClusteringTag: 'ALGORITHM',
    techClusteringTitle: 'DBSCAN CLUSTERING',
    dbscanQuestion:  'Why DBSCAN?',
    dbscanAnswer:    'Unlike K-Means, DBSCAN does not require pre-specifying cluster count and can discover arbitrarily shaped clusters while identifying noise points — ideal for spatial innovation data with irregular distributions.',
    chapterFour:     'CHAPTER FOUR',
    chapterFourTitle: 'GENERALIZATION & APPLICATION',
    chapterFourDesc: 'Transferring the Shanghai-trained model to Fuxing Island\'s renewal design.',
    sourceDomain:    'SOURCE DOMAIN',
    targetDomain:    'TARGET DOMAIN',
    modelGeneralization: 'MODEL GENERALIZATION',
    shanghaiCentral: 'SHANGHAI CENTRAL',
    fuxingIslandName: 'FUXING ISLAND',
    clusteringResult: 'Clustering Result',
    renewalZoning:   'Renewal Zoning',
    ctaBtnText:      'ENTER GENERATION TOOL',
    strategyLabel:   'STRATEGY',

    // ── Indicators Dictionary ─────────────────────────────────────
    'Building Density': 'Building Density',
    'Ratio of building area to total area': 'Ratio of building area to total area',
    'Avg Building Height': 'Avg Building Height',
    'Average building height': 'Average building height',
    'Cafe Count': 'Cafe Count',
    'Number of cafes': 'Number of cafes',
    'Consumer Nearest': 'Consumer Nearest',
    'Distance to nearest consumer facility': 'Distance to nearest consumer facility',
    'Cultural Nearest': 'Cultural Nearest',
    'Distance to nearest cultural facility': 'Distance to nearest cultural facility',
    'FAR Proxy': 'FAR Proxy',
    'Floor area ratio proxy': 'Floor area ratio proxy',
    'GDP Grid Value': 'GDP Grid Value',
    'GDP per grid cell': 'GDP per grid cell',
    'High-tech Count': 'High-tech Count',
    'Number of high-tech enterprises': 'Number of high-tech enterprises',
    'House Price Mean': 'House Price Mean',
    'Average house price': 'Average house price',
    'Infrastructure Nearest': 'Infrastructure Nearest',
    'Distance to nearest infrastructure': 'Distance to nearest infrastructure',
    'Innovation Land Share': 'Innovation Land Share',
    'Share of innovation land use': 'Share of innovation land use',
    'Land Use Shannon': 'Land Use Shannon',
    'Land use diversity index': 'Land use diversity index',
    'Metro Nearest': 'Metro Nearest',
    'Distance to nearest metro station': 'Distance to nearest metro station',
    'Natural Nearest': 'Natural Nearest',
    'Distance to nearest natural space': 'Distance to nearest natural space',
    'Social Nearest': 'Social Nearest',
    'Distance to nearest social facility': 'Distance to nearest social facility',
    'Identity': 'Identity',
    'Sense of place identity': 'Sense of place identity',
    'Innovation Atmosphere': 'Innovation Atmosphere',
    'Perceived innovation atmosphere': 'Perceived innovation atmosphere',
    'Spatial Image': 'Spatial Image',
    'Spatial image perception': 'Spatial image perception',
    'Tech Influence': 'Tech Influence',
    'Technology influence perception': 'Technology influence perception',
    'Work Efficiency': 'Work Efficiency',
    'Perceived work efficiency': 'Perceived work efficiency',
    'Work Wellbeing': 'Work Wellbeing',
    'Work wellbeing perception': 'Work wellbeing perception'
  },

  zh: {
    // ── NavBar ──────────────────────────────────────────────────
    navCompare:   '对比',
    navGenerate:  '生成',
    navAnalyze:   '分析',
    navMethod:    '方法',

    // ── ModelTrainingOverview ────────────────────────────────────
    row01Title:     '模型训练与频繁模式总览',
    methodPipeline: '1. 空间推演方法链',
    defaultSteps: [
      '场景原图',
      'OvSGTR 场景结构',
      'gSpan 频繁子图挖掘',
      'Pattern-count 特征化',
      'XGBoost 空间评分',
      'TreeSHAP 贡献度分析'
    ],
    trainingAssetsTag: 'TRAINING ASSETS',
    trainImages:   '训练图像样本数',
    trainFeatures: 'gSpan 提取特征数',
    cvRmse:        '交叉验证均方根误差 (CV RMSE):',
    cvR2:          '交叉验证确定系数 (CV R²):',
    holdoutR2:     '独立测试集 R² (Holdout R²):',
    fitShapTag:    'FIT & GLOBAL SHAP SUMMARY (DOUBLED SCATTER & IMPORTANCE BAR)',
    scatterPlot:   '预测拟合散点图 (Scatter Plot)',
    shapRanking:   'SHAP 特征全局重要性排行 (Top 20)',
    patternSection:'2. 核心空间子图模式排行',
    patternTip:    '点击下方频繁子图卡片，可将其锁定，联动右侧"单图优化证据链"进行空间缺陷的高亮剖析。',
    posTitle:      '推动评分提升模式 (Top Positive by SHAP)',
    negTitle:      '拉低评分抑制模式 (Top Negative by SHAP)',
    support:       '支持度 (Support)',
    freq:          '子图频数 (Freq)',
    closeModal:    '点击任意空白处关闭弹窗',

    // ── SingleCaseEvidenceChain ──────────────────────────────────
    row03Title:    '单图空间设计评估与优化证据链',
    stageBefore:   'Before 优化前',
    stageBeforeSub:'原图及缺陷诊断',
    stagePlanned:  'Planned 计划优化',
    stagePlannedSub:'反事实模式计划',
    stageObserved: 'Observed 优化后',
    stageObservedSub:'实际成效对比',
    imageViewTag:  'IMAGE VIEW & DETECTED BBOX (空间检测与视觉重构)',
    patternLockHint: '已锁定模式:',
    noPatternHint: '点击左侧模式卡片锁定后，此处将高亮相关空间要素。',
    shapWaterfall: 'SHAP WATERFALL (模型打分决策及特征贡献瀑布图)',
    sceneGraph:    '场景图',
    caseSelector:  '案例选择',
    selectCase:    '请选择一个案例开始分析',
    loading:       '正在加载案例数据...',
    sceneGraphTopology: '场景语义关系图谱',
    cyTip:         '拖拽节点可调整布局 · 鼠标悬浮查看语义关系',
    spatialDiagnosticReport: 'SPATIAL DIAGNOSTIC REPORT (城市设计诊断及优化动作)',
    defectDiagnosis: '城市设计缺陷分析 (Spatial Defect Diagnosis)',
    plannedActions:  '空间优化方向与 AIGC 修改提示 (Planned Actions)',
    observedOutcomes: '实际成效对比与评估 (Observed Outcomes)',
    plannedGain:     '计划提升:',
    actualGain:      '实际提升:',
    noReportData:    '暂无诊断报告数据',

    // ── GpsCaseSelector ──────────────────────────────────────────
    row02Title:      'GPS 案例空间分类检索',
    gpsSiteLegend:   '复兴岛老旧厂房实测 EXIF 地理点位',
    waterfront:      '滨水空间',
    publicSpace:     '公共空间',
    heritage:        '景观/工业遗存',
    temporary:       '临时构筑',
    gpsType:         '类型:',

    // ── GeneratePage ──────────────────────────────────────────────
    pageSubtitle:    'AIGC 城市设计评估与推演大盘 · 科学回溯证据链演示平台',
    integrityAlert:  '数据完整性校验提示 (Missing Files Checked by sync script):',

    // ── MetricsDisplay ────────────────────────────────────────────
    unitItem:        '个',
    entityAdd:       '空间实体增加',
    entityRemove:    '空间实体压制/消减',

    // ── AbovePage ─────────────────────────────────────────────────
    heroTitle:       '复兴岛',
    heroSubtitle:    '创新引力场',
    heroDesc:        '从数据诊断到空间激活 —— 基于多模态指标的创新空间识别',
    exploreBtn:      '开始探索',
    screensTitle:    '案例画廊',
    screensDesc:     '优化前 VS AIGC 视觉重建',
    sceneLegendTitle: '区域图例',
    legendCore:      '核心创新区',
    legendActivated: '待激活潜力区',
    legendTrigger:   '潜在触发表',
    legendDevelopment: '开发中区域',
    sceneHint:       '拖拽旋转 · 滚轮缩放',

    // ── StatList ──────────────────────────────────────────────────
    statisticsTag:   '统计数据',
    indicatorAnalysisTitle: '指标分析度量',
    dataPoints:      '数据格网点',
    studyArea:       '研究区域',
    resolution:      '空间分辨率',
    gridsUnit:       '个格网单元',
    centralShanghai: '上海市中心城区',
    'MEAN VALUE':    '平均数值',
    'STD DEVIATION': '空间标准差',
    'HIGH VALUE':    '高值比例',
    'LOW VALUE':     '低值比例',

    // ── AnalysisPage ──────────────────────────────────────────────
    dataIntelligence: '空间数据智能诊断',
    spatialTitle:    '空间指标网络分布评估',
    spatialSubtitle: '上海中心城区城市创新活力要素收集与聚类可视化分析大屏',
    explicitSource:  '显性物理指标 — 15个空间维度（用地、密度、可达性等）',
    implicitSource:  '隐性感知指标 — 6个大模型图像街景感知特征（认同感、效率等）',
    quadrantTitle:   '空间类型聚类划分与算法训练样本',
    quadrantMap:     '空间四大象限聚类图谱',
    explicitImplicit: '显性物理 × 隐性感知',
    trainingDataSamples: 'AI模型算法训练数据样本',
    regionStatistics: '区域统计概况',
    samplesBadge:    '个样本点',
    totalBadge:      '总计',
    quadrantQ1:      '双高空间 (高显性 & 高隐性)',
    quadrantQ2:      '感性空间 (低显性 & 高隐性)',
    quadrantQ3:      '双低空间 (低显性 & 低隐性)',
    quadrantQ4:      '理性空间 (高显性 & 低隐性)',

    // ── MethodPage ────────────────────────────────────────────────
    methodBrand:     '研究方法论',
    chapterOne:      '第一章',
    chapterOneTitle: '算法分析框架',
    chapterOneDesc:  '融合显性地理空间POI、路网密度以及隐性图像感知等多源测度，建立分类模型用以自动提取上海市域内部复杂的空间特质类型。',
    coreIdeaText:    '本研究创新性构建了融合“显性物理-隐性感知”的综合指标体系，对上海中心城区进行无监督空间聚类，解析不同象限的创新空间模式，并将其成果外推应用于杨浦复兴岛的城市更新设计中。',
    chapterTwo:      '第二章',
    chapterTwoTitle: '数据指标底座体系',
    chapterTwoDesc:  '包含物理空间和人本感知的两大基底，共细分为 14 个核心评估维度。',
    explicitIndicatorsTitle: '显性结构指标',
    implicitIndicatorsTitle: '隐性人本感知指标',
    dimensionsCount8: '8 个结构维度',
    dimensionsCount6: '6 个感知维度',
    llmNoteText:     '注：隐性感知测度指标均由视觉大语言模型 (VLM/LLM) 深入提取街景图像中表现人本交往氛围特征的六维语义矢量聚合产生。',
    chapterThree:    '第三章',
    chapterThreeTitle: '机器学习与算法流程',
    chapterThreeDesc: '基于视觉大语言模型提取隐性感知表征，以及基于密度的 DBSCAN 无监督算法对空间进行聚类。',
    techPipelineTag: '算法流程',
    techPipelineTitle: '大模型图像语义感知分析流',
    techInput:       '输入数据',
    techInputVal:    '现场采集街景图像',
    techProcess:     '核心引擎',
    techProcessVal:  '大语言/视觉模型 (VLM)',
    techProcessSub:  '多模态图像-文本对齐理解与打分',
    techOutput:      '输出数据',
    techOutputVal:   '6维空间品质感知向量',
    techClusteringTag: '聚类分析',
    techClusteringTitle: 'DBSCAN 空间密度聚类',
    dbscanQuestion:  '为什么选择 DBSCAN 算法？',
    dbscanAnswer:    '与传统的 K-Means 聚类不同，DBSCAN 算法不需要预先主观指定聚类簇数，并且能够自主学习和识别任何奇异形状的空间簇，且具备天然过滤空间随机分布噪声点的高效能力，非常适用于结构错综复杂的城市创新功能地段分析。',
    chapterFour:     '第四章',
    chapterFourTitle: '空间模式迁移与应用',
    chapterFourDesc: '将基于上海中心城区整体训练所得的模型推演应用到杨浦复兴岛，指导精准设计。',
    sourceDomain:    '算法源域 (Source Domain)',
    targetDomain:    '推演目标域 (Target Domain)',
    modelGeneralization: '机器学习模型外推推广',
    shanghaiCentral: '上海市域中心城区',
    fuxingIslandName: '复兴岛全岛',
    clusteringResult: '机器学习聚类特征分布',
    renewalZoning:   '城市更新分区定位',
    ctaBtnText:      '进入 AI 空间设计与推演大盘',
    strategyLabel:   '空间设计导则策略',

    // ── Indicators Dictionary ─────────────────────────────────────
    'Building Density': '建筑密度',
    'Ratio of building area to total area': '建筑基底面积与格网总面积的比值',
    'Avg Building Height': '平均建筑高度',
    'Average building height': '格网单元内建筑物平均层高高度',
    'Cafe Count': '咖啡馆数量',
    'Number of cafes': '代表非正式交流网络活力的格网咖啡馆总数',
    'Consumer Nearest': '最近消费可达性',
    'Distance to nearest consumer facility': '格网中心至最近消费服务网点的步行距离',
    'Cultural Nearest': '最近文化可达性',
    'Distance to nearest cultural facility': '格网中心至最近文化活动设施的步行距离',
    'FAR Proxy': '容积率估算代理',
    'Floor area ratio proxy': '空间层数与建筑覆盖度加权后的容积率估算',
    'GDP Grid Value': 'GDP格网产值',
    'GDP per grid cell': '根据多源遥感估算的格网经济GDP总产值',
    'High-tech Count': '高新技术企业数',
    'Number of high-tech enterprises': '格网内高新技术创新企业注册与办公分布数',
    'House Price Mean': '住宅均价',
    'Average house price': '反映地价溢价水平的住宅成交平均单价',
    'Infrastructure Nearest': '市政基础设施距离',
    'Distance to nearest infrastructure': '至最近关键公共基础设施的物理距离',
    'Innovation Land Share': '创新用地比例',
    'Share of innovation land use': '科研用地与商业创新用地占格网面积的份额',
    'Land Use Shannon': '土地利用多样性熵',
    'Land use diversity index': '基于香农熵计算的多功能用地混合混合程度',
    'Metro Nearest': '地铁站最近距离',
    'Distance to nearest metro station': '至最近轨道交通出入口的物理距离',
    'Natural Nearest': '绿地水体可达性',
    'Distance to nearest natural space': '至最近生态绿地、江河水体或公园的步行距离',
    'Social Nearest': '最近社交可达性',
    'Distance to nearest social facility': '至最近社区公共交往与文娱场所的步行距离',
    'Identity': '场所认同感',
    'Sense of place identity': '街景中表征社区归属与地方依恋的感知倾向评分',
    'Innovation Atmosphere': '创新氛围感知',
    'Perceived innovation atmosphere': '街景中科技产业、现代创新设计要素的视觉感知评分',
    'Spatial Image': '空间意象美感',
    'Spatial image perception': '街景环境美学质量与城市设计地标感评分',
    'Tech Influence': '科技渗透感知',
    'Technology influence perception': '表征智慧科技和创新活力对物理界面的渗透评分',
    'Work Efficiency': '工作效率感知',
    'Perceived work efficiency': '物理空间对创新交流和日常通勤便利支持的视觉评分',
    'Work Wellbeing': '工作幸福感',
    'Work wellbeing perception': '反映户外空间舒适性与舒缓压力体验的视觉感知评分'
  }
}

// ─── 公开 API ────────────────────────────────────────────────────
export function useLang() {
  const t = (key) => messages[state.lang][key] ?? messages['en'][key] ?? key

  const toggleLang = () => {
    state.lang = state.lang === 'en' ? 'zh' : 'en'
  }

  const setLang = (l) => {
    if (l === 'en' || l === 'zh') state.lang = l
  }

  const currentLang = computed(() => state.lang)

  return { t, toggleLang, setLang, currentLang, state }
}
